### ISSUE TITLE
`$` in class name can't be handled by janino

### ISSUE THREAD

**Issue by chaokunyang** [janino-compiler/janino#102]
# `$` in class name can't be handled by janino
Using following code:
```java
     @Test
    public void compile() throws Exception {
        CompileUnit unit1 = new CompileUnit("demo.pkg1", "A$$1", (
                "package demo.pkg1;\n" +
                "import demo.pkg2.*;\n" +
                "public class A$$1 {\n" +
                "    public static String main() { return B$$1.hello(); }\n" +
                "    public static String hello() { return \"HELLO\"; }\n" +
                "}"
                ));
        CompileUnit unit2 = new CompileUnit("demo.pkg2", "B$$1", (
                "package demo.pkg2;\n" +
                "import demo.pkg1.*;\n" +
                "public class B$$1 {\n" +
                "    public static String hello() { return A$$1.hello(); }\n" +
                "}"
                ));
        ClassLoader classLoader = compile(Thread.currentThread().getContextClassLoader(), unit1, unit2);
        Assert.assertEquals("HELLO",
                classLoader.loadClass("demo.pkg1.A$$1").getMethod("main").invoke(null));
    }

    public static ClassLoader compile(ClassLoader parentClassLoader, CompileUnit... compileUnits) {
        MapResourceFinder sourceFinder = new MapResourceFinder();
        for (CompileUnit unit : compileUnits) {
            String stubFileName = unit.pkg.replace(".", "/") + "/" + unit.mainClassName + ".java";
            sourceFinder.addResource(stubFileName, unit.getCode());
        }

        // Storage for generated bytecode
        final Map<String, byte[]> classes = new HashMap<>();
        // Set up the compiler.
        ClassLoaderIClassLoader iClassLoader = new ClassLoaderIClassLoader(parentClassLoader);
        org.codehaus.janino.Compiler compiler = new Compiler(sourceFinder, iClassLoader);
        compiler.setClassFileCreator(new MapResourceCreator(classes));
        compiler.setClassFileFinder(new MapResourceFinder(classes));

        // Compile all sources
        try {
            compiler.compile(sourceFinder.resources().toArray(new Resource[0]));
        } catch (CompileException | IOException e) {
            throw new RuntimeException(e);
        }

        // Set up a class loader that finds and defined the generated classes.
        return new ByteArrayClassLoader(classes, parentClassLoader);
    }

public class CompileUnit {
    String pkg;
    String mainClassName;
    private String code;
    private Supplier<String> genCodeFunc;

    public CompileUnit(String pkg, String mainClassName, String code) {
        this.pkg = pkg;
        this.mainClassName = mainClassName;
        this.code = code;
    }

    public CompileUnit(String pkg, String mainClassName, Supplier<String> genCodeFunc) {
        this.pkg = pkg;
        this.mainClassName = mainClassName;
        this.genCodeFunc = genCodeFunc;
    }

    public String getCode() {
        if (code == null) {
            Preconditions.checkNotNull(genCodeFunc);
            code = genCodeFunc.get();
        }
        return code;
    }

    @Override
    public String toString() {
        return "CompileUnit{" + "pkg='" + pkg + '\'' +
                ", mainClassName='" + mainClassName + '\'' +
                '}';
    }
}

```
Get Exceptions:
```java
Caused by: org.codehaus.commons.compiler.CompileException: File 'demo/pkg1/A$$1.java', Line 4, Column 46: Unknown variable or type "B$$1"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12211)
	at org.codehaus.janino.UnitCompiler.getType2(UnitCompiler.java:6860)
	at org.codehaus.janino.UnitCompiler.access$13600(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$22.visitPackage(UnitCompiler.java:6472)
	at org.codehaus.janino.UnitCompiler$22.visitPackage(UnitCompiler.java:6469)
	at org.codehaus.janino.Java$Package.accept(Java.java:4248)
	at org.codehaus.janino.UnitCompiler.getType(UnitCompiler.java:6469)
	at org.codehaus.janino.UnitCompiler.getType2(UnitCompiler.java:6855)
	at org.codehaus.janino.UnitCompiler.access$14200(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$22$2$1.visitAmbiguousName(UnitCompiler.java:6497)
	at org.codehaus.janino.UnitCompiler$22$2$1.visitAmbiguousName(UnitCompiler.java:6494)
	at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4224)
	at org.codehaus.janino.UnitCompiler$22$2.visitLvalue(UnitCompiler.java:6494)
	at org.codehaus.janino.UnitCompiler$22$2.visitLvalue(UnitCompiler.java:6490)
	at org.codehaus.janino.Java$Lvalue.accept(Java.java:4148)
	at org.codehaus.janino.UnitCompiler$22.visitRvalue(UnitCompiler.java:6490)
	at org.codehaus.janino.UnitCompiler$22.visitRvalue(UnitCompiler.java:6469)
	at org.codehaus.janino.Java$Rvalue.accept(Java.java:4116)
	at org.codehaus.janino.UnitCompiler.getType(UnitCompiler.java:6469)
	at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:9026)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5062)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4423)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4396)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5073)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4396)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5662)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2649)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1504)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1487)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3563)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1487)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1567)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3388)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1357)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1330)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:822)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:432)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:411)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:406)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1414)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:406)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:378)
	at org.codehaus.janino.Compiler.compile(Compiler.java:532)
	at com.alipay.streaming.runtime.fury.codegen.JaninoUtilsTest.compile(JaninoUtilsTest.java:61)
	... 23 more
```

It seems that when  classname has`$`,  janino can't find the class with name `$` included when compile multi source code.

When I change compileUnit to this, no error:
```java
        CompileUnit unit1 = new CompileUnit("demo.pkg1", "A$$1", (
                "package demo.pkg1;\n" +
                        "import demo.pkg2.*;\n" +
                        "public class A$$1 {\n" +
                        "    public static String main() { return B.hello(); }\n" +
                        "    public static String hello() { return \"HELLO\"; }\n" +
                        "}"
        ));
        CompileUnit unit2 = new CompileUnit("demo.pkg2", "B", (
                "package demo.pkg2;\n" +
                        "import demo.pkg1.*;\n" +
                        "public class B {\n" +
                        "    public static String hello() { return \"HELLO\"; }\n" +
                        "}"
        ));
```
This suggests that classname can't have`$` when it references by other source code.
Is there any solution or workaround for this?

**Comment by aunkrig** [comment]
Hey Chaokun,

I believe I fixed the problem. The reason being was that `$` in class or interface names is also the separator for member and anonymous class names, and parsing these is non-trivial.

Please test!

**Comment by chaokunyang** [comment]
Hi aunkrig,
  Thanks for your reply, It's the janino version that I used caused the problem. I used 3.0.11.
After switched to 3.1.0-SNAPSHOT master, everything is ok.

**Comment by richard-steiger** [comment]
After pulling from master, I'm getting a strange maven failure when 
trying to compile commons-compiler:

[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with 
nexus-staging-maven-plugin
[INFO]
[INFO] ----------------< org.codehaus.janino:commons-compiler 
 >----------------
[INFO] Building commons-compiler 3.1.0-SNAPSHOT
[INFO] --------------------------------[ jar 
]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ 
commons-compiler ---
[INFO] Deleting T:\janino\commons-compiler\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ 
commons-compiler ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory 
T:\janino\commons-compiler\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3:compile (default-compile) @ 
commons-compiler ---
[INFO] Compiling 96 source files to 
T:\janino\commons-compiler\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac,  but could not parse the error:
The system cannot find the path specified.

[INFO] 1error
[INFO] -------------------------------------------------------------
[INFO] 
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] 
------------------------------------------------------------------------
[INFO] Total time:  2.984 s
[INFO] Finished at: 2019-09-09T10:25:27-07:00
[INFO] 
------------------------------------------------------------------------
[ERROR] Failed to execute goal 
org.apache.maven.plugins:maven-compiler-plugin:2.3:compile 
(default-compile) on project commons-compiler: Compilation failure
[ERROR] Failure executing javac,  but could not parse the error:
[ERROR] The system cannot find the path specified.
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the 
-e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, 
please read the following articles:
[ERROR] [Help 1] 
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException


This is after purging nexus-staging-maven-plugin:1.6.7, totally repeatable.

Any ideas?

Thanks,

-rjs

**Comment by chaokunyang** [comment]
I have a failure when `mvn install`. It's the `JAVA_HOME` configured in pom.xml. After deleted it, everything is ok.  It seems they are different failure.

**Comment by aunkrig** [comment]
I eliminated the hard-coded JAVAC path in "janino-parent/pom.xml".
Please test!
