### ISSUE TITLE
ClassLoaderIClassLoader 's ClassNotFoundException handle mechanism enhancement

### ISSUE THREAD

**Issue by gr4ve** [janino-compiler/janino#104]
```java
Class<?> clazz;
        try {
             clazz = Class.forName(Descriptor.toClassName(descriptor),
                           false, this.classLoader);
        } catch (ClassNotFoundException e) {
            if (e.getException() == null) {
                return null;
            } else
            {
                throw e;
            }
        }
```
in some osgi environment, the e.getException() will return a ClassNotFoundException too.
can we add an additional condition to handle above case?

```java
Class<?> clazz;
        try {
             clazz = Class.forName(Descriptor.toClassName(descriptor),
                           false, this.classLoader);
        } catch (ClassNotFoundException e) {
            if (e.getException() == null || e.getException() instanceof ClassNotFoundException) {
                return null;
            } else
            {
                throw e;
            }
        }
```

**Comment by oontvoo** [comment]
Are you able to share the reproducible case?

I'm not sure it's a good idea to hide multiple upstream exceptions like this ... It could make debugging issues harder in the future

**Comment by aunkrig** [comment]
The aim is to distinguish between „Class does not exist“ and „exception when loading the class“, when the JRE maps both cases to `ClassNotFoundException`.

I‘ll change the code as requested (it is a good pattern to wrap exception X in another exception X in order to augment the message).

**Comment by aunkrig** [comment]
I fixed it:
```
            // Determine whether the class DOES NOT EXIST, or whether there were problems loading it. That's easier
            // said than done... the following seems to work:
            // (See also https://github.com/janino-compiler/janino/issues/104).
            {
                Throwable t = e.getCause();
                while (t instanceof ClassNotFoundException) t = t.getCause();
                if (t == null) return null;
            }
```
Please test!

**Comment by agroh1** [comment]
Thanks very much for this fix.  I ran into this issue on a Spark cluster when using the old version and thought I would leave a stack trace so that people could find this issue more easily.

`Caused by: org.codehaus.commons.compiler.CompileException: Line 11, Column 21: FunctionUtils
  at org.codehaus.janino.UnitCompiler.findTypeByName(UnitCompiler.java:8473)
  at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8712)
  at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8381)
  at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8384)
  at org.codehaus.janino.UnitCompiler.reclassify(UnitCompiler.java:8244)
  at org.codehaus.janino.UnitCompiler.getType2(UnitCompiler.java:6768)
  at org.codehaus.janino.UnitCompiler.access$14100(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$21$2$1.visitAmbiguousName(UnitCompiler.java:6410)
  at org.codehaus.janino.UnitCompiler$21$2$1.visitAmbiguousName(UnitCompiler.java:6407)
  at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4213)
  at org.codehaus.janino.UnitCompiler$21$2.visitLvalue(UnitCompiler.java:6407)
  at org.codehaus.janino.UnitCompiler$21$2.visitLvalue(UnitCompiler.java:6403)
  at org.codehaus.janino.Java$Lvalue.accept(Java.java:4137)
  at org.codehaus.janino.UnitCompiler$21.visitRvalue(UnitCompiler.java:6403)
  at org.codehaus.janino.UnitCompiler$21.visitRvalue(UnitCompiler.java:6382)
  at org.codehaus.janino.Java$Rvalue.accept(Java.java:4105)
  at org.codehaus.janino.UnitCompiler.getType(UnitCompiler.java:6382)
  at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:8939)
  at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5060)
  at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4421)
  at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4394)
  at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5062)
  at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4394)
  at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5575)
  at org.codehaus.janino.UnitCompiler.compileBoolean2(UnitCompiler.java:3986)
  at org.codehaus.janino.UnitCompiler.access$6300(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$14.visitMethodInvocation(UnitCompiler.java:3961)
  at org.codehaus.janino.UnitCompiler$14.visitMethodInvocation(UnitCompiler.java:3933)
  at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5062)
  at org.codehaus.janino.UnitCompiler.compileBoolean(UnitCompiler.java:3933)
  at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2475)
  at org.codehaus.janino.Java$Lvalue.accept(Java.java:4137)
  at org.codehaus.janino.UnitCompiler$21.visitRvalue(UnitCompiler.java:6403)
  at org.codehaus.janino.UnitCompiler$21.visitRvalue(UnitCompiler.java:6382)
  at org.codehaus.janino.Java$Rvalue.accept(Java.java:4105)
  at org.codehaus.janino.UnitCompiler.getType(UnitCompiler.java:6382)
  at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:8939)
  at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5060)
  at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4421)
  at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4394)
  at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5062)
  at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4394)
  at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5575)
  at org.codehaus.janino.UnitCompiler.compileBoolean2(UnitCompiler.java:3986)
  at org.codehaus.janino.UnitCompiler.access$6300(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$14.visitMethodInvocation(UnitCompiler.java:3961)
  at org.codehaus.janino.UnitCompiler$14.visitMethodInvocation(UnitCompiler.java:3933)
  at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5062)
  at org.codehaus.janino.UnitCompiler.compileBoolean(UnitCompiler.java:3933)
  at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2475)
  at org.codehaus.janino.UnitCompiler.access$1900(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$6.visitIfStatement(UnitCompiler.java:1495)
  at org.codehaus.janino.UnitCompiler$6.visitIfStatement(UnitCompiler.java:1487)
  at org.codehaus.janino.Java$IfStatement.accept(Java.java:2947)
  at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1487)
  at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1567)
  at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1553)
  at org.codehaus.janino.UnitCompiler.access$1700(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1493)
  at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1487)
  at org.codehaus.janino.Java$Block.accept(Java.java:2776)
  at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1487)
  at org.codehaus.janino.UnitCompiler.compileTryCatch(UnitCompiler.java:3136)
  at org.codehaus.janino.UnitCompiler.compileTryCatchFinally(UnitCompiler.java:2966)
  at org.codehaus.janino.UnitCompiler.compileTryCatchFinallyWithResources(UnitCompiler.java:2770)
  at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2742)
  at org.codehaus.janino.UnitCompiler.access$2300(UnitCompiler.java:215)
  at org.codehaus.janino.UnitCompiler$6.visitTryStatement(UnitCompiler.java:1499)
  at org.codehaus.janino.UnitCompiler$6.visitTryStatement(UnitCompiler.java:1487)
  at org.codehaus.janino.Java$TryStatement.accept(Java.java:3238)
Caused by: java.lang.ClassNotFoundException: FunctionUtils
  at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:84)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.codehaus.janino.ClassLoaderIClassLoader.findIClass(ClassLoaderIClassLoader.java:89)
  at org.codehaus.janino.IClassLoader.loadIClass(IClassLoader.java:312)
  at org.codehaus.janino.UnitCompiler.findTypeByName(UnitCompiler.java:8469)
  ... 127 more
Caused by: java.lang.ClassNotFoundException: FunctionUtils
  at java.lang.ClassLoader.findClass(ClassLoader.java:524)
  at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
  at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:30)
  at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:79)
  ... 134 more`
