### ISSUE TITLE
org.codehaus.commons.compiler.CompileException: Non-abstract class "SC$1" must implement method 

### ISSUE THREAD

**Issue by zhangbinzaifendou** [janino-compiler/janino#109]
janino version:3.1.0
flink version:1.9.1
java version:1.8
java code:
```
 @Test
    public void testPattern() throws Exception {
        ExpressionEvaluator evaluator = new ExpressionEvaluator();
        evaluator.setParentClassLoader(this.getClass().getClassLoader());
        evaluator.setReturnType(Pattern.class);
        evaluator.cook("import org.apache.flink.*;\n" +
                "import org.apache.flink.cep.*;\n" +
                "import org.apache.flink.cep.pattern.*;\n" +
                "import org.apache.flink.cep.pattern.conditions.SimpleCondition;\n" +
                "import org.apache.flink.api.common.functions.FilterFunction.*;\n" +
                "import org.apache.flink.streaming.api.windowing.time.Time;\n" +
                "import java.io.*;\n" +
                "import java.lang.*;\n" +
                "import java.net.*;\n" +
                "import java.util.*;\n" +
                "import net.xxx.flinkcep.Event;\n" +
                "Pattern.<Event>begin(\"first\")\n" +
                "                .where(new SimpleCondition<Event>() {\n" +
                "                    @Override\n" +
                "                    public boolean filter(Event value) throws Exception {\n" +
                "                        return value.getEvent().equals(\"xfd\");\n" +
                "                    }\n" +
                "                })\n" +
                "                .next(\"second\").where(new SimpleCondition<Event>() {\n" +
                "                    @Override\n" +
                "                    public boolean filter(Event value) throws Exception {\n" +
                "                        return value.getEvent().equals(\"mxffy\");\n" +
                "                    }\n" +
                "                })\n" +
                "                .followedBy(\"end\").where(new SimpleCondition<Event>() {\n" +
                "                    @Override\n" +
                "                    public boolean filter(Event value) throws Exception {\n" +
                "                        return value.getEvent().equals(\"xxxx\");\n" +
                "                    }\n" +
                "                }).within(Time.seconds(20)).timesOrMore(3)");
        Pattern pattern = (Pattern) evaluator.evaluate(new Pattern[]{});
        System.out.println(pattern.toString());
```
Event.java
```
public class Event {
    private String driverId;
    private String event;
    private long timestamp;

    public Event(String driverId, String event, int timestamp) {
        this.driverId = driverId;
        this.event = event;
        this.timestamp = timestamp;
    }

    public String getDriverId() {
        return driverId;
    }

    public String getEvent() {
        return event;
    }

    public long getTimestamp() {
        return timestamp;
    }

    @Override
    public String toString() {
        return "Event{" +
                "driverId='" + driverId + '\'' +
                ", event='" + event + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Event) {
            Event other = (Event) obj;
            return driverId.equals(other.driverId) && event == other.event && timestamp == other.timestamp;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(driverId, event, timestamp);
    }
}
```
exception:
```
org.codehaus.commons.compiler.CompileException: Line 13, Column 51: Non-abstract class "SC$1" must implement method "public abstract boolean org.apache.flink.api.common.functions.FilterFunction.filter(java.lang.Object) throws java.lang.Exception"

	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12021)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:481)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:975)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:945)
	at org.codehaus.janino.UnitCompiler.access$200(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:387)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:384)
	at org.codehaus.janino.Java$AnonymousClassDeclaration.accept(Java.java:1289)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:384)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5530)
	at org.codehaus.janino.UnitCompiler.access$9500(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitNewAnonymousClassInstance(UnitCompiler.java:4491)
	at org.codehaus.janino.UnitCompiler$16.visitNewAnonymousClassInstance(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$NewAnonymousClassInstance.accept(Java.java:5451)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5175)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5140)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4482)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4455)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5286)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4455)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5683)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2652)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1507)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1490)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3758)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1490)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1573)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3420)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1362)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1335)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:807)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:410)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:389)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:384)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1594)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:384)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:362)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:226)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:336)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:333)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:363)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:333)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:235)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:464)
	at org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:314)
	at org.codehaus.janino.ScriptEvaluator.cook2(ScriptEvaluator.java:727)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:716)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:663)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:631)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:205)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:80)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:75)
	at net.xxx.janino.Hello.testPattern(Hello.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```
package org.apache.flink.cep.pattern.conditions;
![image](https://user-images.githubusercontent.com/7866431/71310569-a60bdb80-2450-11ea-9a38-c36c6b36e6e9.png)
package org.apache.flink.api.common.functions;
![image](https://user-images.githubusercontent.com/7866431/71310574-ac01bc80-2450-11ea-87da-094e624b7f1d.png)

In my code:
![image](https://user-images.githubusercontent.com/7866431/71310647-5b3e9380-2451-11ea-9833-b7330aacbd0c.png)

**Comment by aunkrig** [comment]
Example code requires the following additional dependencies:

* org.apache.flink:flink-cep_2.12 (version 1.9.1)
* org.apache.flink:flink-streaming-java_2.12 (version>1.9.1)

**Comment by aunkrig** [comment]
Exception reproduced. Same exception in lines 13, 19 and 25.

**Comment by aunkrig** [comment]
Hey ZhangBin,

thank you for reporting this bug! The reason for the problem is JANINO's poor support for generics: It doesn't understand that

    new SimpleCondition<Event>() {
        @Override public boolean filter(Event value) throws Exception {
            ...

actually overrides `boolean filter(Object)`.

The simple (yet ugly) workaround is to declare the method differently:

    new SimpleCondition<Event>() {
        @Override public boolean filter(Object o) throws Exception { Event value = (Event) o;
            ...

Is that feasible for you?


CU Arno

**Comment by aunkrig** [comment]
(Internal notice: The symptoms and the cure are exactly the same for the current JANINO version, 3.1.1-SNAPSHOT.)

**Comment by zhangbinzaifendou** [comment]
ths
