### ISSUE TITLE
Script evaluating does not work for java 11 when there is annotation processor

### ISSUE THREAD

**Issue by nikolayandr** [janino-compiler/janino#129]
When a script is evaluated within java 11 and lombok is added as annotation processor then an NPE exception is occurred on call of **reset()** for **com.sun.tools.javac.code.Symbol.ModuleSymbol#module_info**

Stacktrace:
```
java.lang.NullPointerException
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$1.visitTopLevel(JavacProcessingEnvironment.java:1543)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:529)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$1.scan(JavacProcessingEnvironment.java:1527)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.newRound(JavacProcessingEnvironment.java:1263)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:1061)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:1100)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1337)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.commons.compiler.jdk.SimpleCompiler.cook(SimpleCompiler.java:358)
	at org.codehaus.commons.compiler.jdk.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:219)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:514)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:425)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:52)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:650)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:614)
```

Let me explain what exactly happens in the code:
```
                boolean isModuleInfo = node.sourcefile.isNameCompatible("module-info", Kind.SOURCE);
                if (isModuleInfo) {
                    node.modle.reset();
                    node.modle.completer = sym -> modules.enter(List.of(node), node.modle.module_info);
                    node.modle.module_info.reset();
                    node.modle.module_info.members_field = WriteableScope.create(node.modle.module_info);
                }
```

**node.sourcefile** holds through **com.sun.tools.javac.api.ClientCodeWrapper.WrappedFileObject#clientFileObject** instance of **org.codehaus.commons.compiler.jdk.SimpleCompiler**(which nests java script) which method **isNameCompatible()** always returns true, so it looks it should not be treated as module info file

**Comment by nikolayandr** [comment]
Is there anyone alive here?

**Comment by aunkrig** [comment]
I could not easily reproduce the problem, but your fix passes the regression test suite, so I integrated it.

An official version that includes your fix will be released soon. For the time being, you may use the HEAD version.

**Comment by nikolayandr** [comment]
Cool
