### ISSUE TITLE
AssertionError for SimpleCompiler.cook when using DeepCopier

### ISSUE THREAD

**Issue by karussell** [janino-compiler/janino#135]
I'm probably doing something wrong. I stumbled over this problem when I tried to change a method via the DeepCopier but the problem already occurs for the variable declaration so I left out everything unrelated.

See the following code:

```java
Java.AbstractCompilationUnit cu = new Parser(new Scanner("Test", new StringReader(""
        + "public class Test {"
        + "   int blup;"
        + "}"))).
        parseAbstractCompilationUnit();
cu = new DeepCopier().copyAbstractCompilationUnit(cu);
SimpleCompiler sc = new SimpleCompiler();
boolean works = false;
if (works) {
    StringWriter sw = new StringWriter();
    Unparser.unparse(cu, sw);
    sc.cook(sw.toString());
} else {
    sc.cook(cu);
}
assertNotNull(sc.getClassLoader().loadClass("Test").getDeclaredConstructor().newInstance());
```

which works for `works=true` but throws an AssertionError for `works=false`:

```
java.lang.AssertionError
	at org.codehaus.janino.Java$Statement.getEnclosingScope(Java.java:3005)
	at org.codehaus.janino.Java$FieldDeclaration.getDeclaringType(Java.java:2815)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2352)
	at org.codehaus.janino.UnitCompiler.access$1500(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitFieldDeclaration(UnitCompiler.java:1497)
	at org.codehaus.janino.UnitCompiler$6.visitFieldDeclaration(UnitCompiler.java:1493)
	at org.codehaus.janino.Java$FieldDeclaration.accept(Java.java:2847)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1493)
	at org.codehaus.janino.UnitCompiler.initializeInstanceVariablesAndInvokeInstanceInitializers(UnitCompiler.java:7589)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3425)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3151)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:810)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:401)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:380)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:375)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1692)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:375)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:348)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:322)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:319)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:367)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:319)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:237)
```

**Comment by karussell** [comment]
I got it working via:

```
 cu = new DeepCopier() {

            @Override
            public Java.FieldDeclaration copyFieldDeclaration(Java.FieldDeclaration subject) throws CompileException {
                Java.FieldDeclaration fd = super.copyFieldDeclaration(subject);
                fd.setEnclosingScope(subject.getEnclosingScope());
                return fd;
            }
        }.copyAbstractCompilationUnit(cu);
```

Is this the correct way to cook a AbstractCompilationUnit?

**Comment by aunkrig** [comment]
Thank you! Merged it.

**Comment by karussell** [comment]
As you reverted this here https://github.com/janino-compiler/janino/commit/4880bf0f53a4284bf5cf486db2dee570c7a8b262 does this mean the way I proposed will be problematic for certain use cases?

**Comment by aunkrig** [comment]
Errr... yes. The enclosing scope of an element must not be set when it is created, but when it is added to its superordinate element. No idea why I didn't understand that when I accepted your fix. Also no idea why I didn't add your test case to the regression test suite, like I always do...

Now I've done it right. Please test.

**Comment by karussell** [comment]
Nice, thanks a lot! This seems to fix it :)

(I've locally built 3.1.7-SNAPSHOT based on latest master and all tests are green [without my workaround](https://github.com/graphhopper/graphhopper/blob/bc573db1251ed21e97642542c218f6c725fe0305/core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java#L346-L352).)
