### ISSUE TITLE
NoSuchMethodError after upgrade to janino 3.1.3

### ISSUE THREAD

**Issue by WellingR** [janino-compiler/janino#142]
I am using the [conditional processing feature of logback](http://logback.qos.ch/manual/configuration.html#conditional) which uses janino under the hood.
I upgraded my janino version from 3.1.2 to 3.1.3 and now the following exception occurs.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'int org.codehaus.commons.compiler.util.SystemProperties.getIntegerClassProperty(java.lang.Class, java.lang.String, int)'
	at org.codehaus.janino.UnitCompiler.<clinit>(UnitCompiler.java:236)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:240)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:267)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:82)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:77)
	at ch.qos.logback.core.joran.conditional.PropertyEvalScriptBuilder.build(PropertyEvalScriptBuilder.java:47)
	at ch.qos.logback.core.joran.conditional.IfAction.begin(IfAction.java:65)
	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
        at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:203)
       ...
```

It appears that janino transitively depends on org.codehaus.janino:commons-compiler:3.1.2 should this perhaps be version 3.1.3?

**Comment by aunkrig** [comment]
I guess that you updated `janino.jar` to 3.1.3, but forgot to update `commons-compiler.jar` accordingly:

```
$ java -cp janino/3.1.3/janino-3.1.3.jar\;commons-compiler/3.1.3/commons-compiler-3.1.3.jar org.codehaus.commons.compiler.samples.ExpressionDemo 'System.currentTimeMillis()'
Result = 1612027293286

$ java -cp janino/3.1.3/janino-3.1.3.jar\;commons-compiler/3.1.2/commons-compiler-3.1.2.jar org.codehaus.commons.compiler.samples.ExpressionDemo 'System.currentTimeMillis()'
Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.commons.compiler.util.SystemProperties.getIntegerClassProperty(Ljava/lang/Class;Ljava/lang/String;I)I
    at org.codehaus.janino.UnitCompiler.<clinit>(UnitCompiler.java:236)
    at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:240)
    at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:861)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:778)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:762)
    at org.codehaus.janino.ExpressionEvaluator.cook(ExpressionEvaluator.java:517)
    at org.codehaus.janino.ExpressionEvaluator.cook(ExpressionEvaluator.java:472)
    at org.codehaus.janino.ExpressionEvaluator.cook(ExpressionEvaluator.java:438)
    at org.codehaus.janino.ExpressionEvaluator.cook(ExpressionEvaluator.java:423)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:82)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:77)
    at org.codehaus.commons.compiler.samples.ExpressionDemo.main(ExpressionDemo.java:129)
$
```

**Comment by arnor2000** [comment]
Our team experience same problem.

As OP said `commons-compiler` is a transitive dependency, we don't explicitly declare commons-compiler version, it comes from `janino-3.1.3.pom`:

`<dependency>
      <groupId>org.codehaus.janino</groupId>
      <artifactId>commons-compiler</artifactId>
      <version>${project.parent.version}</version>
    </dependency>`

It seems `${project.parent.version}` is unexpectedly resolved to `3.1.2` (experienced with Maven 3.6.3).

**Comment by aunkrig** [comment]
I don't get it... `janino-3.1.3.jar!META-INF/maven/org.codehaus.janino/janino/pom.xml` says

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    ....
        <parent>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino-parent</artifactId>
            <version>3.1.3</version>
            <relativePath>../janino-parent</relativePath>
        </parent>
    ...
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>commons-compiler</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

, so `${project.parent.version}´ is definitely "3.1.3". And this has always been working...

Can you please check the content of your `janino-3.1.3.jar!META-INF/maven/org.codehaus.janino/janino/pom.xml`? Is the parent version "3.1.3", as above?

**Comment by WellingR** [comment]
It seems to be caused by including the old commons-compiler in the dependency management:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.group.id</groupId>
    <artifactId>my-project</artifactId>
    <version>3.11.0-SNAPSHOT</version>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.4.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
            <version>3.1.3</version>
        </dependency>
    </dependencies>
</project>
```

running `mvn dependency:tree` then gives the following output

```
[INFO] com.group.id:my-project:jar:3.11.0-SNAPSHOT
[INFO] \- org.codehaus.janino:janino:jar:3.1.3:compile
[INFO]    \- org.codehaus.janino:commons-compiler:jar:3.1.2:compile
```

It appears that the spring-boot-dependencies includes commons-compiler 3.1.2 . And it appears that maven prefers that version over the transitive dependency of janino itself.
For this specific example removing the dependency management fixes the issue.

**Comment by WellingR** [comment]
I am closing this since this is not a janino issue. But weird maven behaviour.

**Comment by aunkrig** [comment]
No offense... I am glad it wasn’t a bug in JANINO, because that would have had really bad consequences...
