### ISSUE TITLE
Strings in switch statement

### ISSUE THREAD

**Issue by laurent149** [janino-compiler/janino#15]
Hello,

In the documentation you say that Janino supports strings in switch statements (Java 7 language features).
However, the following simple test:
```java
    @Test
    public void testSwitch() throws CompileException, InvocationTargetException {
        ScriptEvaluator se = new ScriptEvaluator();
        se.setReturnType(String.class);
        se.cook("switch(\"1\") { case \"1\": return \"42\"; default: return null; }");
        assertEquals("42", se.evaluate(new Object[0]));
    }
```
throws the following:
```
org.codehaus.commons.compiler.CompileException: Line 1, Column 7: Assignment conversion not possible from type "java.lang.String" to type "int"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:11523)
	at org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:10379)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1881)
	at org.codehaus.janino.UnitCompiler.access$2300(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$6.visitSwitchStatement(UnitCompiler.java:1451)
	at org.codehaus.janino.UnitCompiler$6.visitSwitchStatement(UnitCompiler.java:1438)
	at org.codehaus.janino.Java$SwitchStatement.accept(Java.java:3220)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1438)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1518)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2950)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1308)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1281)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:780)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:431)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:385)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:380)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1405)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:380)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:354)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:413)
	at org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:318)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:597)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:489)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:422)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:200)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:76)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:71)
```
Whereas it works perfectly with a simple switch on int:
```java
    @Test
    public void testSwitch() throws CompileException, InvocationTargetException {
        ScriptEvaluator se = new ScriptEvaluator();
        se.setReturnType(String.class);
        se.cook("switch(1) { case 1: return \"42\"; default: return null; }");
        assertEquals("42", se.evaluate(new Object[0]));
    }
```
For information, I'm using the latest version of Janino:
```xml
      <dependency>
          <groupId>org.codehaus.janino</groupId>
          <artifactId>janino</artifactId>
          <version>3.0.6</version>
      </dependency>
```
Am I doing something wrong?

Many thanks for your help!

Laurent

**Comment by aunkrig** [comment]
Err... you're right -- STRING SWITCH is obviously not implemented. I need to check if I implemented it somewhere and forgot to commit... Stay tuned.

**Comment by aunkrig** [comment]
Well, STRING SWITCH turned out to be a "phantom feature" - one that is claimed, but not implemented ;-) .

To make the documentation match reality, i just implemented STRING SWITCH on the MASTER branch - please test!

**Comment by laurent149** [comment]
Tested with the master's 3.0.7-SNAPSHOT version and both above tests are now successful :-)

Many thanks for your super quick feedback and resolution!
