### ISSUE TITLE
Calcite tests fail with compiler error starting with Janino compiler version 3.1.3

### ISSUE THREAD

**Issue by birschick-bq** [janino-compiler/janino#151]
**Environment**: [Calcite (latest)](https://github.com/apache/calcite)
**OS**: Windows
**Janino version**: 3.1.3, and 3.1.4 (not an issue with 3.1.2 or earlier)
**Example test**: [SqlOperatorBaseTest.java ](https://github.com/apache/calcite/blob/f928e073c384010c294370b63ffb748c15caab8a/core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java#L2764)

**Exception call stack**:

```

Error while executing SQL "select (p0,TIMESTAMP '1970-01-01 00:00:00') OVERLAPS (TIMESTAMP '1970-01-01 00:00:00',TIMESTAMP '1970-01-01 00:00:00') from (values (TIMESTAMP '1970-01-01 00:00:00')) as t(p0)": Error while compiling generated Java code:
public org.apache.calcite.linq4j.Enumerable bind(final org.apache.calcite.DataContext root) {
  final org.apache.calcite.linq4j.Enumerable _inputEnumerable = org.apache.calcite.linq4j.Linq4j.asEnumerable(new Long[] {
    0L});
  return new org.apache.calcite.linq4j.AbstractEnumerable(){
      public org.apache.calcite.linq4j.Enumerator enumerator() {
        return new org.apache.calcite.linq4j.Enumerator(){
            public final org.apache.calcite.linq4j.Enumerator inputEnumerator = _inputEnumerable.enumerator();
            public void reset() {
              inputEnumerator.reset();
            }

            public boolean moveNext() {
              return inputEnumerator.moveNext();
            }

            public void close() {
              inputEnumerator.close();
            }

            public Object current() {
              long case_when_value;
              final long current = org.apache.calcite.runtime.SqlFunctions.toLong(inputEnumerator.current());
              final boolean binary_call_value = current <= 0L;
              if (binary_call_value) {
                case_when_value = 0L;
              } else {
                case_when_value = current;
              }
              long case_when_value0;
              if (binary_call_value) {
                case_when_value0 = current;
              } else {
                case_when_value0 = 0L;
              }
              return org.apache.calcite.runtime.SqlFunctions.toBoolean(case_when_value >= 0L && 0L >= case_when_value0);
            }

          };
      }

    };
}


public Class getElementType() {
  return boolean.class;
}



java.sql.SQLException: Error while executing SQL "select (p0,TIMESTAMP '1970-01-01 00:00:00') OVERLAPS (TIMESTAMP '1970-01-01 00:00:00',TIMESTAMP '1970-01-01 00:00:00') from (values (TIMESTAMP '1970-01-01 00:00:00')) as t(p0)": Error while compiling generated Java code:
public org.apache.calcite.linq4j.Enumerable bind(final org.apache.calcite.DataContext root) {
  final org.apache.calcite.linq4j.Enumerable _inputEnumerable = org.apache.calcite.linq4j.Linq4j.asEnumerable(new Long[] {
    0L});
  return new org.apache.calcite.linq4j.AbstractEnumerable(){
      public org.apache.calcite.linq4j.Enumerator enumerator() {
        return new org.apache.calcite.linq4j.Enumerator(){
            public final org.apache.calcite.linq4j.Enumerator inputEnumerator = _inputEnumerable.enumerator();
            public void reset() {
              inputEnumerator.reset();
            }

            public boolean moveNext() {
              return inputEnumerator.moveNext();
            }

            public void close() {
              inputEnumerator.close();
            }

            public Object current() {
              long case_when_value;
              final long current = org.apache.calcite.runtime.SqlFunctions.toLong(inputEnumerator.current());
              final boolean binary_call_value = current <= 0L;
              if (binary_call_value) {
                case_when_value = 0L;
              } else {
                case_when_value = current;
              }
              long case_when_value0;
              if (binary_call_value) {
                case_when_value0 = current;
              } else {
                case_when_value0 = 0L;
              }
              return org.apache.calcite.runtime.SqlFunctions.toBoolean(case_when_value >= 0L && 0L >= case_when_value0);
            }

          };
      }

    };
}


public Class getElementType() {
  return boolean.class;
}



	at org.apache.calcite.avatica.Helper.createException(Helper.java:56)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:163)
	at org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:227)
	at org.apache.calcite.sql.test.SqlOperatorBaseTest$TesterImpl.check(SqlOperatorBaseTest.java:10281)
	at org.apache.calcite.sql.test.AbstractSqlTester.check(AbstractSqlTester.java:464)
	at org.apache.calcite.sql.test.AbstractSqlTester.checkBoolean(AbstractSqlTester.java:433)
	at org.apache.calcite.sql.test.SqlOperatorBaseTest$OverlapChecker.isTrue(SqlOperatorBaseTest.java:10370)
	at org.apache.calcite.sql.test.SqlOperatorBaseTest.checkOverlaps(SqlOperatorBaseTest.java:2768)
	at org.apache.calcite.sql.test.SqlOperatorBaseTest.testPeriodOperators(SqlOperatorBaseTest.java:2764)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:139)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:81)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.RuntimeException: Error while compiling generated Java code:
public org.apache.calcite.linq4j.Enumerable bind(final org.apache.calcite.DataContext root) {
  final org.apache.calcite.linq4j.Enumerable _inputEnumerable = org.apache.calcite.linq4j.Linq4j.asEnumerable(new Long[] {
    0L});
  return new org.apache.calcite.linq4j.AbstractEnumerable(){
      public org.apache.calcite.linq4j.Enumerator enumerator() {
        return new org.apache.calcite.linq4j.Enumerator(){
            public final org.apache.calcite.linq4j.Enumerator inputEnumerator = _inputEnumerable.enumerator();
            public void reset() {
              inputEnumerator.reset();
            }

            public boolean moveNext() {
              return inputEnumerator.moveNext();
            }

            public void close() {
              inputEnumerator.close();
            }

            public Object current() {
              long case_when_value;
              final long current = org.apache.calcite.runtime.SqlFunctions.toLong(inputEnumerator.current());
              final boolean binary_call_value = current <= 0L;
              if (binary_call_value) {
                case_when_value = 0L;
              } else {
                case_when_value = current;
              }
              long case_when_value0;
              if (binary_call_value) {
                case_when_value0 = current;
              } else {
                case_when_value0 = 0L;
              }
              return org.apache.calcite.runtime.SqlFunctions.toBoolean(case_when_value >= 0L && 0L >= case_when_value0);
            }

          };
      }

    };
}


public Class getElementType() {
  return boolean.class;
}



	at org.apache.calcite.avatica.Helper.wrap(Helper.java:37)
	at org.apache.calcite.adapter.enumerable.EnumerableInterpretable.toBindable(EnumerableInterpretable.java:129)
	at org.apache.calcite.prepare.CalcitePrepareImpl$CalcitePreparingStmt.implement(CalcitePrepareImpl.java:1130)
	at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:318)
	at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:215)
	at org.apache.calcite.prepare.CalcitePrepareImpl.prepare2_(CalcitePrepareImpl.java:647)
	at org.apache.calcite.prepare.CalcitePrepareImpl.prepare_(CalcitePrepareImpl.java:513)
	at org.apache.calcite.prepare.CalcitePrepareImpl.prepareSql(CalcitePrepareImpl.java:483)
	at org.apache.calcite.jdbc.CalciteConnectionImpl.parseQuery(CalciteConnectionImpl.java:249)
	at org.apache.calcite.jdbc.CalciteMetaImpl.prepareAndExecute(CalciteMetaImpl.java:623)
	at org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:675)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)
	... 45 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Compiling "Baz" in Line 1, Column 1: Line 1, Column 45: Compiling "bind(org.apache.calcite.DataContext root)": Line 4, Column 10: Compiling "new org.apache.calcite.linq4j.AbstractEnumerable() { ... }": Line 5, Column 51: Compiling "enumerator()": Line 6, Column 16: Compiling "new org.apache.calcite.linq4j.Enumerator() { ... }": Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:369)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:333)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:330)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:367)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:330)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:245)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:267)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:52)
	at org.codehaus.janino.ClassBodyEvaluator.createInstance(ClassBodyEvaluator.java:428)
	at org.apache.calcite.adapter.enumerable.EnumerableInterpretable.getBindable(EnumerableInterpretable.java:164)
	at org.apache.calcite.adapter.enumerable.EnumerableInterpretable.toBindable(EnumerableInterpretable.java:126)
	... 55 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 1, Column 45: Compiling "bind(org.apache.calcite.DataContext root)": Line 4, Column 10: Compiling "new org.apache.calcite.linq4j.AbstractEnumerable() { ... }": Line 5, Column 51: Compiling "enumerator()": Line 6, Column 16: Compiling "new org.apache.calcite.linq4j.Enumerator() { ... }": Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3222)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:412)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:391)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1692)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:359)
	... 68 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 4, Column 10: Compiling "new org.apache.calcite.linq4j.AbstractEnumerable() { ... }": Line 5, Column 51: Compiling "enumerator()": Line 6, Column 16: Compiling "new org.apache.calcite.linq4j.Enumerator() { ... }": Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5731)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2718)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1540)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3886)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3531)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3218)
	... 78 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 5, Column 51: Compiling "enumerator()": Line 6, Column 16: Compiling "new org.apache.calcite.linq4j.Enumerator() { ... }": Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3222)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:977)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:947)
	at org.codehaus.janino.UnitCompiler.access$200(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:389)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$AnonymousClassDeclaration.accept(Java.java:1375)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5571)
	at org.codehaus.janino.UnitCompiler.access$9400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4640)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4604)
	at org.codehaus.janino.Java$NewAnonymousClassInstance.accept(Java.java:5608)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4604)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5729)
	... 87 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 6, Column 16: Compiling "new org.apache.calcite.linq4j.Enumerator() { ... }": Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5731)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2718)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1540)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3886)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3531)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3218)
	... 104 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 20, Column 27: Compiling "current()": Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3222)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:977)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:947)
	at org.codehaus.janino.UnitCompiler.access$200(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:389)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$AnonymousClassDeclaration.accept(Java.java:1375)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5571)
	at org.codehaus.janino.UnitCompiler.access$9400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4640)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4604)
	at org.codehaus.janino.Java$NewAnonymousClassInstance.accept(Java.java:5608)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4604)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5729)
	... 113 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 30, Column 19: Compiling "binary_call_value": Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5731)
	at org.codehaus.janino.UnitCompiler.compileBoolean2(UnitCompiler.java:4201)
	at org.codehaus.janino.UnitCompiler.access$6200(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4151)
	at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4148)
	at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4574)
	at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4148)
	at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4144)
	at org.codehaus.janino.Java$Lvalue.accept(Java.java:4498)
	at org.codehaus.janino.UnitCompiler.compileBoolean(UnitCompiler.java:4144)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2508)
	at org.codehaus.janino.UnitCompiler.access$1900(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitIfStatement(UnitCompiler.java:1531)
	at org.codehaus.janino.UnitCompiler$6.visitIfStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$IfStatement.accept(Java.java:3274)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3531)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3218)
	... 130 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Invalid local variable index 5
	at org.codehaus.janino.UnitCompiler.getLocalVariableTypeInfo(UnitCompiler.java:13207)
	at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12232)
	at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12209)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4679)
	at org.codehaus.janino.UnitCompiler.access$7900(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15$1.visitLocalVariableAccess(UnitCompiler.java:4616)
	at org.codehaus.janino.UnitCompiler$15$1.visitLocalVariableAccess(UnitCompiler.java:4608)
	at org.codehaus.janino.Java$LocalVariableAccess.accept(Java.java:4632)
	at org.codehaus.janino.UnitCompiler$15.visitLvalue(UnitCompiler.java:4608)
	at org.codehaus.janino.UnitCompiler$15.visitLvalue(UnitCompiler.java:4604)
	at org.codehaus.janino.Java$Lvalue.accept(Java.java:4498)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4604)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4675)
	at org.codehaus.janino.UnitCompiler.access$7400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15$1.visitAmbiguousName(UnitCompiler.java:4611)
	at org.codehaus.janino.UnitCompiler$15$1.visitAmbiguousName(UnitCompiler.java:4608)
	at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4574)
	at org.codehaus.janino.UnitCompiler$15.visitLvalue(UnitCompiler.java:4608)
	at org.codehaus.janino.UnitCompiler$15.visitLvalue(UnitCompiler.java:4604)
	at org.codehaus.janino.Java$Lvalue.accept(Java.java:4498)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4604)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5729)
	... 148 more

```

**Comment by aunkrig** [comment]
Could reproduce the problem, and was able to reduce it to this Janino script:

    double  a;       // <= Must be LONG or DOUBLE, and must not be initialized.
    boolean b;       // <= Must be declared *after* "a".
    b = true; a = 1; // <= In *that* order.
    if (b) {}

See `ReportedBugsTest.testIssue151()`.

**Comment by birschick-bq** [comment]
@aunkrig Thanks for looking at this. Any thoughts on root-cause? Is there something that needs to change in Calcite?

**Comment by aunkrig** [comment]
It's definitely a bug in Janino; I'm looking into it.

Man, I curse the person who invented the `StackMapTable` attribute for the JVM...

**Comment by aunkrig** [comment]
Got it! Please test.

That `StackMapTable` thing really is the worst invention since COBOL.

I suppose you want an "offical" Janino release?

**Comment by birschick-bq** [comment]
Awesome! Thanks, Arno.

An "official" release makes my life easier for testing the change. If you're unsure of the change and want me to test without an "official" release, let me know and I'll spend some time on that.

Thanks,
Bruce

**Comment by aunkrig** [comment]
Hey Bruce,

Janino has a huge regression suite, so I’m very sure I have not damaged anything,m. There is no reason to cause any extra efforts for you. I will release a new official version ASAP.

CU Arno

**Comment by aunkrig** [comment]
Janino 3.1.6 is out the door! If you're wondering why 3.1.4 is followed by 3.1.6 and not by 3.1.5, ask the inventors of SONATYPE NEXUS...

Please test!

**Comment by birschick-bq** [comment]
Thanks! Testing...

**Comment by birschick-bq** [comment]
Tests are passing now. Thanks!
On local machine - now able to bundle Calcite in "uber" JAR and it successfully loads the Janino compiler from reading the resource file.

So now just waiting for Calcite to approve, merge and release version using Janinio version 3.1.6.

Thanks for your help!
