### ISSUE TITLE
Enhanced FOR statement does not work with primitive variable

### ISSUE THREAD

**Issue by lixinyuan1213** [janino-compiler/janino#155]
In actual use, I found that the program that implements the Iterable interface cannot be compiled, and the error message is as follows（version:3.1.6）:
`
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'pkg1/A.java', Line 13, Column 17: Compiling "run()": File 'pkg1/A.java', Line 15, Column 9: java.lang.AssertionError
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3222)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:412)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:391)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1692)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:359)
	... 7 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'pkg1/A.java', Line 15, Column 9: java.lang.AssertionError
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1609)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3531)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3218)
	... 17 more
Caused by: java.lang.AssertionError
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1840)
	at org.codehaus.janino.UnitCompiler.access$2100(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitForEachStatement(UnitCompiler.java:1533)
	at org.codehaus.janino.UnitCompiler$6.visitForEachStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ForEachStatement.accept(Java.java:3353)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	... 19 more
`

I abstracted the code, the code is as follows:

StartApp.java:

```
public class StartApp {
    public static void main(String[] args) throws Exception
    {
        ICompiler compiler =  new CompilerFactory().newCompiler();
        Map<String, byte[]> classes = new HashMap<>(4);
        compiler.setClassFileCreator(new MapResourceCreator(classes));
        String s = FileUtil.readUtf8String("C:\\Users\\lisy\\Desktop\\src\\A.java");
        String f = FileUtil.readUtf8String("C:\\Users\\lisy\\Desktop\\src\\RangeList.java");
        compiler.compile(new Resource[] {
                new StringResource(
                        "pkg1/A.java",
                        s
                ),
                new StringResource(
                        "pkg1/RangeList.java",
                        f
                )
        });
        ClassLoader cl = new ResourceFinderClassLoader(
                new MapResourceFinder(classes),
                ClassLoader.getSystemClassLoader()
        );
        Object o = cl.loadClass("pkg1.A").newInstance();
        ((Runnable) o).run();
    }
}

```

A.java

```
public class A implements Runnable{
    @Override
    public void run() {
        RangeList rangeList = new RangeList().push(1,100);
        for(int i:rangeList){
            System.out.println(i);
        }
    }
}
```

RangeList.java

```
public class RangeList implements Iterable<Integer>{
    public RangeList push(int lower, int upper) {
        ranges.add(new Range(lower, upper));
        return this;
    }
    public RangeList push(int range) {
        ranges.add(new Range(range));
        return this;
    }

    @Override
    public Iterator<Integer> iterator() {
        return new RangeListIterator(ranges);
    }

    String toSyntaxString() {
        StringBuilder result = new StringBuilder("new RangeList()");
        for (Range range : ranges) {
            result.append(".push(");
            result.append(range.lower);
            if (range.upper != range.lower) {
                result.append(", ");
                result.append(range.upper);
            }
            result.append(")");
        }
        return result.toString();
    }

    private List<Range> ranges = new ArrayList<>();
}

class Range {
    Range(int lower, int upper) {
        if (lower < 0 || upper < lower) {
            throw new IllegalArgumentException("Illegal Range");
        }
        this.lower = lower;
        this.upper = upper;
    }

    Range(int range) {
        if (range < 0) {
            throw new IllegalArgumentException("Illegal Range");
        }
        this.lower = this.upper = range;
    }

    final int lower, upper;
}


class RangeListIterator implements Iterator<Integer> {
    RangeListIterator(List<Range> rs) {
        iterator = rs.iterator();
        if (iterator.hasNext()) {
            range = iterator.next();
            value = range.lower;
        }
    }
    @Override
    public boolean hasNext() {
        return iterator.hasNext() || range != null;
    }

    @Override
    public Integer next(){
        if (range == null) {
            throw new NoSuchElementException();
        } else {
            Integer result = value;
            if(value == range.upper) {
                if (iterator.hasNext()) {
                    range = iterator.next();
                    value = range.lower;
                } else {
                    range = null;
                }
            } else {
                value += 1;
            }
            return result;
        }
    }

    private Iterator<Range> iterator;
    private Range range;
    private int value;
}
```

**Comment by aunkrig** [comment]
There are two problems in the code to compile.

### Problem #1

    range = iterator.next();

This does not compile due to a (documented) limitation of Janino: It ignores type arguments, and thus complains that the return value of `next()` (which is `Object`) cannot be assigned to variable `range`, which has type `Range`. The workaround is that you add the required type cast:

    range = (Range) iterator.next();

### Problem #2 

    for (int i : rangeList) {

The thing is that the type of `i` is a *primitive* `int`, but the `rangeList` delivers `Object`s. Janino attempt "assignment conversion", and "narrowing reference conversion", but not (yet) "unboxing conversion", which is required here.

One possible workaround would be to declare ì` with type `Integer`:

    for (Integer i : rangeList) {

. But I will now add the missing attempt of unboxing conversion.

Stay tuned.

**Comment by aunkrig** [comment]
Hey Lisy,


I just fixed problem #2 (Janino now also attempts unboxing conversion). Do you need a Janino release, or can you live with the workaround for the time being?


CU Arno

**Comment by aunkrig** [comment]
Ping.

**Comment by lixinyuan1213** [comment]
> Ping.

Thank you very much for your work. I would love to use the code from this project in future projects

**Comment by aunkrig** [comment]
You are welcome!

**Comment by penttin** [comment]
Hello,

Maybe the same issue with long and double arrays?
```
long[] test = new long[2];
for (long i : test) {
   System.out.println(i);
 }
```
It throws an InternalCompilerException: Invalid local variable index 8

This works: 
```
int[] test = new int[2];
for (int i : test) {
  System.out.println(i);
}
```
