### ISSUE TITLE
error message should include variable/field names for clarity

### ISSUE THREAD

**Issue by oontvoo** [janino-compiler/janino#16]
When a variable with "default" access modifier is accessed from outside the declaring file, we get this error.

It'd be clearer if the error message include the name of the field.

```

 Caused by: org.codehaus.commons.compiler.CompileException: File 'Unknown', Line -1, Column -1: Member with "/*default*/" access cannot be accessed from type "com.exampl.MyApp"
         at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:11004)
         at org.codehaus.janino.UnitCompiler.checkAccessible(UnitCompiler.java:6464)
         at org.codehaus.janino.UnitCompiler.checkAccessible(UnitCompiler.java:6440)
         at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:3828)
         at org.codehaus.janino.UnitCompiler.access$8800(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$12.visitFieldAccess(UnitCompiler.java:3793)
         at org.codehaus.janino.UnitCompiler$12.visitFieldAccess(UnitCompiler.java:3762)
         at org.codehaus.janino.Java$FieldAccess.accept(Java.java:3709)
         at org.codehaus.janino.Java$Lvalue.accept(Java.java:3563)
         at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:3762)
         at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4270)
         at org.codehaus.janino.UnitCompiler.access$8900(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$12.visitFieldAccessExpression(UnitCompiler.java:3794)
         at org.codehaus.janino.UnitCompiler$12.visitFieldAccessExpression(UnitCompiler.java:3762)
         at org.codehaus.janino.Java$FieldAccessExpression.accept(Java.java:3975)
         at org.codehaus.janino.Java$Lvalue.accept(Java.java:3563)
         at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:3762)
         at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:4933)
         at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4476)
         at org.codehaus.janino.UnitCompiler.access$7500(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$12.visitMethodInvocation(UnitCompiler.java:3774)
         at org.codehaus.janino.UnitCompiler$12.visitMethodInvocation(UnitCompiler.java:3762)
         at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:4328)
         at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:3762)
         at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:4933)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3180)
         at org.codehaus.janino.UnitCompiler.access$5000(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$9.visitMethodInvocation(UnitCompiler.java:3151)
         at org.codehaus.janino.UnitCompiler$9.visitMethodInvocation(UnitCompiler.java:3139)
         at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:4328)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3139)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2112)
         at org.codehaus.janino.UnitCompiler.access$1700(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1377)
         at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1370)
         at org.codehaus.janino.Java$ExpressionStatement.accept(Java.java:2558)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1370)
         at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1450)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1436)
         at org.codehaus.janino.UnitCompiler.access$1600(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1376)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1370)
         at org.codehaus.janino.Java$Block.accept(Java.java:2471)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1370)
         at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1450)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1436)
         at org.codehaus.janino.UnitCompiler.access$1600(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1376)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1370)
         at org.codehaus.janino.Java$Block.accept(Java.java:2471)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1370)
         at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1450)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1436)
         at org.codehaus.janino.UnitCompiler.access$1600(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1376)
         at org.codehaus.janino.UnitCompiler$6.visitBlock(UnitCompiler.java:1370)
         at org.codehaus.janino.Java$Block.accept(Java.java:2471)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1370)
         at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1450)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2811)
         at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1262)
         at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1234)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:538)
         at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:420)
         at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:206)
         at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:374)
         at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:369)
         at org.codehaus.janino.Java$AbstractPackageMemberClassDeclaration.accept(Java.java:1309)
         at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:369)
         at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:345)
         at com.streambase.sb.codegen.JaninoCompiler.compile(JaninoCompiler.java:88)
         at com.streambase.sb.codegen.CGCompiler.generateBinaryClasses(CGCompiler.java:201)
         at com.streambase.sb.codegen.CompilationUnit.compile(CompilationUnit.java:176)
         ... 7 more
```

**Comment by aunkrig** [comment]
Hi Vy,
the error message is now prefixed with the class and field being accessed. Please test!

CU Arno

**Comment by oontvoo** [comment]
Hi Arno, worked as expected. Thanks!
