### ISSUE TITLE
After a successful compilation, compiling identical (or similar) code fails with an assignment conversion error

### ISSUE THREAD

**Issue by JoshRosen** [janino-compiler/janino#167]
I've encountered a confusing compile error which appears to involve some sort of "statefulness" in Janino: I'm able to successfully compile a given piece of code, but following that compilation I run into errors when trying to compile similar code.

The following code reproduces the problem on both Janino 3.1.7 and 3.0.16:

```java
import org.codehaus.janino.ClassBodyEvaluator;

public class Main {

  // These two code snippets differ only in identifier names:
  static String code1 = "class Test1 { void foo1() { Object x1 = null; byte[] arr1 = null; x1 = arr1.toString(); } }";
  static String code2 = "class Test2 { void foo2() { Object x2 = null; byte[] arr2 = null; x2 = arr2.toString(); } }";

  static void compile(String code) {
    try {
      ClassBodyEvaluator evaluator = new ClassBodyEvaluator();
      evaluator.cook(code);
      System.out.println("Compilation successful");
    } catch (Exception e) {
      e.printStackTrace(System.out);
    }
  }

  public static void main(String[] args) {
    System.out.println("\nFirst compilation:");
    compile(code1);

    System.out.println("\nSecond compilation:");
    compile(code2);
  }
}
```

This prints:

```
First compilation:
Compilation successful

Second compilation:
org.codehaus.commons.compiler.CompileException: Line 1, Column 67: Assignment conversion not possible from type "java.lang.String" to type "java.lang.Object"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12874)
	at org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:11145)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3975)
	at org.codehaus.janino.UnitCompiler.access$6200(UnitCompiler.java:234)
	at org.codehaus.janino.UnitCompiler$10.visitAssignment(UnitCompiler.java:3933)
	at org.codehaus.janino.UnitCompiler$10.visitAssignment(UnitCompiler.java:3913)
	at org.codehaus.janino.Java$Assignment.accept(Java.java:4853)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3913)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2403)
	at org.codehaus.janino.UnitCompiler.access$1800(UnitCompiler.java:234)
	at org.codehaus.janino.UnitCompiler$5.visitExpressionStatement(UnitCompiler.java:1528)
	at org.codehaus.janino.UnitCompiler$5.visitExpressionStatement(UnitCompiler.java:1521)
	at org.codehaus.janino.Java$ExpressionStatement.accept(Java.java:3206)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1521)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1605)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3560)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3235)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1389)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1362)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:806)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:983)
	at org.codehaus.janino.UnitCompiler.access$700(UnitCompiler.java:234)
	at org.codehaus.janino.UnitCompiler$2.visitMemberClassDeclaration(UnitCompiler.java:400)
	at org.codehaus.janino.UnitCompiler$2.visitMemberClassDeclaration(UnitCompiler.java:392)
	at org.codehaus.janino.Java$MemberClassDeclaration.accept(Java.java:1532)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:392)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMemberTypes(UnitCompiler.java:1339)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:841)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:418)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:234)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:397)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:392)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1687)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:392)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:365)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:234)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:339)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:336)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:370)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:336)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:254)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:267)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:82)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:77)
	at Main.compile(Main.java:12)
	at Main.main(Main.java:24)
```

I still get the same failure if I swap the order in which the two classes are compiled: each class successfully compiles when compiled first and fails when compiled second. The problem also occurs if identical code is used in both compilations.

I'm wondering whether there's some of global state in Janino which accounts for this behavior (e.g. some sort of cache of 

I try to add a cast `x1 = (String) arr1.toString();` then I get the following error on the second compilation:

```
org.codehaus.commons.compiler.CompileException: Line 1, Column 79: Cannot cast "java.lang.String" to "java.lang.String"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12874)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5107)
        [...]
```

**Comment by aunkrig** [comment]
That's fantastic! Many, many years ago a similar problem occurred, maybe related to #32, but only sporadically. I'll look into this soon.

**Comment by aunkrig** [comment]
Was able to reduce the test even more:
```
    @Test public void
    testIssue167() throws Exception {
        new ScriptEvaluator().cook("double[] arr1;        /* <= any primitive array */                                   ");
        new ScriptEvaluator().cook("double[] arr2 = null; /* <= same primitive array type */ Object x2 = arr2.toString();");
    }
```

**Comment by aunkrig** [comment]
The condition appears to be the use of primitive arrays (in your case, `byte[]`, in my case, `double[]`).
```
    @Test public void
    testIssue167() throws Exception {
        new ScriptEvaluator().cook("double[] /* <= any primitive array */ arr1;");
        new ScriptEvaluator().cook("Object x2 = ((double[] /* <= same primitive array type */) null).toString();");
    }
```

**Comment by aunkrig** [comment]
Moved the `getArrayIClass(...)` methods from `IClass` to `IClassLoader`, and keep the array classes per-class-loader (which is important because arrays refer to `java.lang.Object`).

Also added a test case.

**Please test!**

**Comment by JoshRosen** [comment]
I tested my real code against a snapshot Janino build and can confirm that this change resolves the compilation errors. Thanks for the fix!

**Comment by aunkrig** [comment]
My pleasure. Thanks for the precise bug report!

Do you want a release, or is it enough that the fix is on the HEAD?

**Comment by JoshRosen** [comment]
Just the fix on HEAD is fine for me, since I'm not actually blocked by this issue.

It turns out that the original source code which uncovered this bug was, itself, being generated due to a higher-level bug in our own application. After fixing that issue, we no longer emit source code which triggers this issue.

**Comment by aunkrig** [comment]
FYI: Janino 3.1.8 is out the door, and it includes your fix.
