### ISSUE TITLE
Janino incorrectly thinks variables are uninitialized

### ISSUE THREAD

**Issue by cvogt729** [janino-compiler/janino#178]
I'm using Janino 3.1.7 with `SimpleCompiler` to compile and execute the following code:
```java
public class test3 {
  public static void main(String[] args){
    double a;
    for (int i=0;i<3;++i){
      a=i;
      System.out.println(a);
    }
  }
}
```
When invoking `SimpleCompiler` in Windows PowerShell with OpenJDK 11.0.14.1:
```powershell
java '-cp' 'janino-3.1.7.jar;commons-compiler-3.1.7.jar' 'org.codehaus.janino.SimpleCompiler' 'test3.java' 'test3'
```
I get the following error:
```
Exception in thread "main" org.codehaus.commons.compiler.InternalCompilerException: Compiling "test3" in File 'test3.java', Line 1, Column 8: File 'test3.java', Line 2, Column 22: Compiling "main(String[] args)": File 'test3.java', Line 4, Column 18: Compiling "i": Invalid local variable index 3
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:375)
        at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:339)
        at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:336)
        at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:370)
        at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:336)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:254)
        at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:491)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:232)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:210)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:70)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:59)
        at org.codehaus.janino.SimpleCompiler.<init>(SimpleCompiler.java:149)
        at org.codehaus.janino.SimpleCompiler.main(SimpleCompiler.java:112)
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test3.java', Line 2, Column 22: Compiling "main(String[] args)": File 'test3.java', Line 4, Column 18: Compiling "i": Invalid local variable index 3
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3239)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1389)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1362)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:806)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:418)
        at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:397)
        at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:392)
        at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1687)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:392)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:365)
        ... 13 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test3.java', Line 4, Column 18: Compiling "i": Invalid local variable index 3
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5765)
        at org.codehaus.janino.UnitCompiler.compileBoolean2(UnitCompiler.java:4358)
        at org.codehaus.janino.UnitCompiler.access$6700(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$11.visitBinaryOperation(UnitCompiler.java:4155)
        at org.codehaus.janino.UnitCompiler$11.visitBinaryOperation(UnitCompiler.java:4133)
        at org.codehaus.janino.Java$BinaryOperation.accept(Java.java:5238)
        at org.codehaus.janino.UnitCompiler.compileBoolean(UnitCompiler.java:4133)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1712)
        at org.codehaus.janino.UnitCompiler.access$2000(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$5.visitForStatement(UnitCompiler.java:1530)
        at org.codehaus.janino.UnitCompiler$5.visitForStatement(UnitCompiler.java:1521)
        at org.codehaus.janino.Java$ForStatement.accept(Java.java:3326)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1521)
        at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1605)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3560)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3235)
        ... 23 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Invalid local variable index 3
        at org.codehaus.janino.UnitCompiler.getLocalVariableTypeInfo(UnitCompiler.java:13390)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12421)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12396)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4668)
        at org.codehaus.janino.UnitCompiler.access$8100(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$13$1.visitLocalVariableAccess(UnitCompiler.java:4605)
        at org.codehaus.janino.UnitCompiler$13$1.visitLocalVariableAccess(UnitCompiler.java:4597)
        at org.codehaus.janino.Java$LocalVariableAccess.accept(Java.java:4650)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4597)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4593)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4517)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4593)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4664)
        at org.codehaus.janino.UnitCompiler.access$7600(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4600)
        at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4597)
        at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4592)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4597)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4593)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4517)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4593)
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5763)
        ... 38 more
```
The error goes away when you replace `double` with `int`.

**Comment by aunkrig** [comment]
Man, `StackMapTable` is an exemplar for bad data structure design: When SUN invented Java, they decided that `double` and `long` occupy *two* slots on the operand stack and in the local variables array (a not-so-good design decision, because it adds complexity and bears no advantages for any but the very first JVM).

But then came the `StackMapTable` attribute, which tracks the changes on the operand stack and the local variables array, and SUN decided to discard that pattern, and that `double` and `long` entries now take up only *one* slot. Great! Complexity reduced! Complexity reduced? No: When slots are re-used, their type changes. And iff the new/old slot is `double` or `long`, and the old/new isnt't, then two slots must be replaced with one  slot (or vice versa). How brilliant! And happy testing...

Did I mention before that I hate `StackMapTable`?

I added the handling for that case, and also a test case with your code, and that works now. Can you please test if there are more edge cases that still don't work?

**Comment by cvogt729** [comment]
This issue is resolved. Thank you! I'll continue to look for edge cases.
