### ISSUE TITLE
Compilation of vars initialized in different if/else branches is failing

### ISSUE THREAD

**Issue by snuyanzin** [janino-compiler/janino#187]
During upgrade to Calcite 1.28.0 (janino 3.1.6) i noticed that code containing such snippet starts failing in compiliation with janino (also reproducible with 3.1.8)
```java
...
long result$5;
boolean isNull$5;
if (false || false) {
   result$5 = -1L;
    isNull$5 = true;
}
else {
    isNull$4 = row$1.isNullAt(0);
    field$4 = -1L;
     if (!isNull$4) {
        field$4 = row$1.getLong(0);
     }
     result$5 = field$4;
     isNull$5 = isNull$4;
}
...
```
at the same time if i remove dead branch of if and try once again e.g.
```java
...
long result$5;
boolean isNull$5;
isNull$4 = row$1.isNullAt(0);
field$4 = -1L;
 if (!isNull$4) {
    field$4 = row$1.getLong(0);
 }
 result$5 = field$4;
 isNull$5 = isNull$4;
...
```
it starts working again.
At the same time both code snippets are compiling with 3.0.11

the full stacktrace
```
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Compiling "StreamExecCalc$6" in Line 2, Column 14: Line 43, Column 21: Compiling "processElement(org.apache.flink.streaming.runtime.streamrecord.StreamRecord element)"
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:402)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:363)
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:361)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:371)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:361)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:264)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:517)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:241)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:219)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:82)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:77)
	at org.apache.flink.table.runtime.generated.CompileUtils.doCompile(CompileUtils.java:104)
	... 25 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 43, Column 21: Compiling "processElement(org.apache.flink.streaming.runtime.streamrecord.StreamRecord element)"
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3296)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1430)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1403)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:829)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:442)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:422)
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:418)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1688)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:418)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:392)
	... 37 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Line 75, Column 15
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1648)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3621)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3292)
	... 47 more
Caused by: java.lang.AssertionError: J
	at org.codehaus.janino.CodeContext.popOperand(CodeContext.java:1495)
	at org.codehaus.janino.CodeContext.popOperandAssignableTo(CodeContext.java:1536)
	at org.codehaus.janino.UnitCompiler.invoke(UnitCompiler.java:12417)
	at org.codehaus.janino.UnitCompiler.invokeMethod(UnitCompiler.java:13101)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5351)
	at org.codehaus.janino.UnitCompiler.access$9300(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4698)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4674)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5470)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4674)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5817)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:4053)
	at org.codehaus.janino.UnitCompiler.access$6100(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:4028)
	at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:4003)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5470)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:4003)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2487)
	at org.codehaus.janino.UnitCompiler.access$1800(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1563)
	at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1558)
	at org.codehaus.janino.Java$ExpressionStatement.accept(Java.java:3209)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1558)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1644)
	... 49 more
```

**Comment by snuyanzin** [comment]
was able to reproduce it with this class
```java
public class MyClass {
    public static void test() {
        boolean b;
        if (false) {
            b = true;
        } else {
            b = false;
        }
        System.out.println(b);
    }
}

```

**Comment by snuyanzin** [comment]
i'm not 100% sure however this one could be related to https://github.com/janino-compiler/janino/issues/186

**Comment by aunkrig** [comment]
Reproduced (`org.codehaus.commons.compiler.tests.ReportedBugsTest.testIssue187()`).

Could well be that fixing #187 will also fix #186... we will see.

**Comment by aunkrig** [comment]
Fixed. Please test.

**Comment by snuyanzin** [comment]
awesome, thanks!
tested, now Flink tests which failed with this issue before are passing.
And yes #186 also seems fixed since it is not reproduced with that fix

**Comment by snuyanzin** [comment]
@aunkrig thank you again for the fixes!
I don't know how difficult it is to cope with https://github.com/janino-compiler/janino/issues/188
In case it is, may I ask you to make a new release?
I'm asking because exactly this issue is the main pain point to workaround it in Flink code while with 2 others it's just a couple of lines change

**Comment by aunkrig** [comment]
I'm still working on #188; I will make a release for you as requested.

**Comment by aunkrig** [comment]
I'm desperately trying to release Janino 3.1.9, but oss.sonatype.org won't let me... 401!

No idea what is wrong there. Will try again tomorrow, maybe time heals the wounds.

**Comment by aunkrig** [comment]
I can deploy "commons-compiler-jdk-3.1.9.pom", but not "commons-compiler-jdk-3.1.9.jar". Repeatedly. And it is not the company internet proxy's fault - I get the same error when I do it on a machine with a direct internet connection. Sigh...

**Comment by snuyanzin** [comment]
ok I see... 
I guess the only thing that could be done is trying again...
At least no more ideas...

**Comment by aunkrig** [comment]
Janino 3.1.9 is out the door... enjoy!
