### ISSUE TITLE
For ExpressionEvaluator, doesn't allow null values

### ISSUE THREAD

**Issue by exprEval** [janino-compiler/janino#30]
I am using Janino library to evaluate expressions fed by user dynamically. Sometimes values passed to expression can be null, while executing expression get following exception:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:929)	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:349)
..
..
..

Caused by: java.lang.NullPointerException
	at SC.eval0(Unknown Source)
	... 9 more

Expression: (a != null && a.equals("MATCH"))?true:false

Wile executing sometimes values of a can be null, but expression doesn't get executed since a is null. How could we get this working?

**Comment by aunkrig** [comment]
You're right; the expression evaluation should not throw an MPE.

Could you please provide a minimal code example that reproduces the problem?

**Comment by exprEval** [comment]
Ok, so I upgraded to Janino 3.0.0 and now I don't see the issue. Thanks.
