### ISSUE TITLE
java.lang.StackOverflowError when loading some java code

### ISSUE THREAD

**Issue by zolyfarkas** [janino-compiler/janino#4]
java.lang.StackOverflowError
	at org.codehaus.janino.Java$NormalAnnotation.setEnclosingScope(Java.java:389)
	at org.codehaus.janino.Java$NormalAnnotation.setEnclosingScope(Java.java:389)
	at org.codehaus.janino.Java$NormalAnnotation.setEnclosingScope(Java.java:389)
	at org.codehaus.janino.Java$NormalAnnotation.setEnclosingScope(Java.java:389)
	at org.codehaus.janino.Java$NormalAnnotation.setEnclosingScope(Java.java:389)

looking at the code, it looks like a infinite loop:

        @Override public void
        setEnclosingScope(Scope enclosingScope) { this.setEnclosingScope(enclosingScope); }

Findbugs would complain about it....

I am using janino 2.7.8

**Comment by zolyfarkas** [comment]
Just tested with 3.0.1 and this issues looks like it is fixed
