### ISSUE TITLE
Issue with scriptEvaluator compilation.

### ISSUE THREAD

**Issue by chaitanyaekre** [janino-compiler/janino#49]
**Hi,
I am getting an exception as**
	_Exception in thread "main" java.lang.ClassFormatError: Too many arguments in method signature in class file SC
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at org.codehaus.janino.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:81)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:319)
    at org.codehaus.janino.ScriptEvaluator.cook2(ScriptEvaluator.java:609)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:598)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:534)
    at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:503)
    at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:204)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:80)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:75)
    at org.codehaus.janino.ScriptEvaluator.<init>(ScriptEvaluator.java:165)
    at ScriptComplier.main(ScriptComplier.java:23)

	I am using scriptEvaluator(block,returntype,parametername,parametertype) to which I am passing two arrays parametername and parametertype both of the size 1000.And script String length 74324.
	I have attached the sample code file. Please guide me on this. Is there any other way to achieve this

[ScriptComplier.txt](https://github.com/janino-compiler/janino/files/2062787/ScriptComplier.txt)

**Comment by aunkrig** [comment]
Hi,

the JVM supports only up to 255 parameters:

https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.3.3


CU Arno

**Comment by chaitanyaekre** [comment]
Hey thanks for the reply, but I have more than 255 parameters so is there any way or trick that you can suggest to achieve this??

**Comment by aunkrig** [comment]
Just pass your parameters in ONE array parameter.
