### ISSUE TITLE
Assertion error for public static final field declaration

### ISSUE THREAD

**Issue by zolyfarkas** [janino-compiler/janino#6]
Here is the scope:
(org.codehaus.janino.Java$FieldDeclaration) public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"requiredEnum\",\"namespace\":\"test\",\"symbols\":[\"a\",\"b\"]}");

I am not sure what Janino does not like here...

**Comment by aunkrig** [comment]
Would you please (A) paste the error message and call stack and (B) present a code example that reproduces the problem.

**Comment by zolyfarkas** [comment]
Yes sorry about not providing this originally, Here is the full stack trace:

java.lang.AssertionError: SCHEMA$
	at org.codehaus.janino.UnitCompiler.invokeConstructor(UnitCompiler.java:7424)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4862)
	at org.codehaus.janino.UnitCompiler.access$8900(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$12.visitNewClassInstance(UnitCompiler.java:3971)
	at org.codehaus.janino.UnitCompiler$12.visitNewClassInstance(UnitCompiler.java:3932)
	at org.codehaus.janino.Java$NewClassInstance.accept(Java.java:4991)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:3932)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5115)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4654)
	at org.codehaus.janino.UnitCompiler.access$8200(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$12.visitMethodInvocation(UnitCompiler.java:3959)
	at org.codehaus.janino.UnitCompiler$12.visitMethodInvocation(UnitCompiler.java:3932)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:4874)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:3932)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5115)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2222)
	at org.codehaus.janino.UnitCompiler.access$1400(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$6.visitFieldDeclaration(UnitCompiler.java:1432)
	at org.codehaus.janino.UnitCompiler$6.visitFieldDeclaration(UnitCompiler.java:1428)
	at org.codehaus.janino.Java$FieldDeclaration.accept(Java.java:2510)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1428)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1508)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2940)
	at org.codehaus.janino.UnitCompiler.maybeCreateInitMethod(UnitCompiler.java:1250)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:650)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:435)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberEnumDeclaration(UnitCompiler.java:392)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberEnumDeclaration(UnitCompiler.java:381)
	at org.codehaus.janino.Java$PackageMemberEnumDeclaration.accept(Java.java:1603)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:381)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:354)
	at org.codehaus.janino.JavaSourceClassLoader.generateBytecodes(JavaSourceClassLoader.java:226)
	at org.codehaus.janino.JavaSourceClassLoader.findClass(JavaSourceClassLoader.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.spf4j.beans.GenericRecordBuilder.createClass(GenericRecordBuilder.java:30)
	at org.spf4j.beans.GenericRecordBuilderTest.testGenericRecordCreation(GenericRecordBuilderTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

here are the files that I am trying to compile:

[test.zip](https://github.com/janino-compiler/janino/files/465969/test.zip)

Here is the code, so that you can see how janino is being used:

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-experimental/src/main/java/org/spf4j/beans/GenericRecordBuilder.java

+

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-experimental/src/test/java/org/spf4j/beans/GenericRecordBuilderTest.java

You should be able to clone the project build and run the unit test to reproduce the problem.

**Comment by aunkrig** [comment]
Got it! This error occured iff a field initializer contains a "new class instance" expression.
The minimal test case looks like this:
```
	public enum MyEnum {
	  A, B;
	  Object notAnEnumConstant = new Object();
	}
```
Also added a test case in "ReportedBugs.java".

**Comment by zolyfarkas** [comment]
Thank you!
