### ISSUE TITLE
How to use ExpressionEvaluator.cook(String[])?

### ISSUE THREAD

**Issue by karussell** [janino-compiler/janino#64]
The javadocs say:
```
    /**
     * Same as {@link #cook(String)}, but for multiple scripts.
     */
```

But when I use the latest master and I do:

```java
ExpressionEvaluator ee = new ExpressionEvaluator();
ee.setStaticMethod(false);//without this there is not error
ee.cook("9*3;7+1".split(";"));
```

I get

```
! java.lang.IllegalArgumentException: null
! at org.codehaus.janino.ScriptEvaluator.array(ScriptEvaluator.java:775)
! at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:550)
! at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:535)
! at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:500)
! at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:473)
! at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:466)
```

And how would I define a variable? The following does not work:

```
ee.cook("int tmp = 3;tmp*7+1".split(";"));
```

**Comment by aunkrig** [comment]
It's not a bug, it's a feature ;-) !
You should have called `setStaticMethod(new boolean[] { false, false })` - then it works.
Admittedly, the error message is not too helpful... I just improved it:

```
java.lang.IllegalArgumentException: Inconsistent script count; previously 1, now 2
```

**Comment by aunkrig** [comment]
If you want to use variables, then it's no longer an "expression", but a "script":
```
new ScriptEvaluator().cook("int tmp = 3; return tmp * 7 + 1;").evaluate(null);
```

**Comment by karussell** [comment]
>  You should have called setStaticMethod(new boolean[] { false, false }) - then it works.

Ah, does this mean that with this method I define two expressions and I access them via ee.getMethod(idx)?

> If you want to use variables, then it's no longer an "expression", but a "script":

Got it - thanks!

**Comment by karussell** [comment]
Years later ;) ... just wanted to write the code here for the record as it took me quite a while to get it working again ... I was searching for the following use case and missed the setExpressionTypes method otherwise I got `Non-abstract class "SC" must implement method "public abstract double SomeInterface.calc(double)"`. Maybe this can be added to the javadocs? And what is the difference to the return type?

```java
public abstract class BaseClass implements SomeInterface {
    public static int a, b;
}

...

public interface SomeInterface {
    double calc(double c);
}

...

IExpressionEvaluator ee = new ExpressionEvaluator();
ee.setOverrideMethod(new boolean[]{
        true,
});
ee.setStaticMethod(new boolean[]{
        false,
});
ee.setExpressionTypes(new Class[]{
        double.class,
});
ee.setExtendedClass(BaseClass.class);
//ee.setImplementedInterfaces(new Class[]{SomeInterface.class,});
ee.setMethodNames(new String[]{
        "calc",
});
ee.setParameters(new String[][]{
        {"c"},
}, new Class[][]{
        {double.class},
});

ee.cook(new String[]{
        "a + b + 2 * c",
});

// init once
BaseClass.a = 2;
BaseClass.b = 3;

// but instance is decoupled
SomeInterface instance = (SomeInterface) ee.getClazz().getDeclaredConstructor().newInstance();
assertEquals(13, instance.calc(4));

SomeInterface instance2 = (SomeInterface) ee.getClazz().getDeclaredConstructor().newInstance();
assertEquals(85, instance2.calc(40));
assertEquals(21, instance.calc(8));
assertEquals(45, instance2.calc(20));
```
