### ISSUE TITLE
compilation failure: sensitivity to classpath order and packaging naming

### ISSUE THREAD

**Issue by stuarthalloway** [janino-compiler/janino#68]
Starting with Janino 3.0.7, it appears that Janino is sometimes unable to see classes on the classpath. I have created an [automated repro](https://github.com/Datomic/janino-repro-3) with a more complete description.

Please let me know if I can provide any additional help or information.

Cheers,
Stu

**Comment by aunkrig** [comment]
Was able to reproduce with the HEAD version:

```
$ ./run-repro
================================
Run 1. Compiled classes:
target/classes
target/classes/datomic
target/classes/datomic/JaninoRepro3.class
Class location:
jar:file:/C:/Server/mavenrepo/junit/junit/4.12/junit-4.12.jar!/junit/framework/TestCase.class
Classpath:
target/classes:C:\Server\mavenrepo\junit\junit\4.12\junit-4.12.jar;C:\dev\EclipseWS\janino\commons-compiler\target\classes;C:\dev\EclipseWS\janino\commons-compiler-jdk\target\classes;C:\Server\mavenrepo\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;./target/classes;C:/Server/mavenrepo/junit/j
unit/4.12/junit-4.12.jar
Run trivial script:
123
================================
Run 2. Compiled classes:
target/classes
target/classes/datomic
target/classes/datomic/JaninoRepro3.class
target/classes/junit
target/classes/junit/framework
target/classes/junit/framework/subpackage
target/classes/junit/framework/subpackage/Breaker.class
Class location:
jar:file:/C:/Server/mavenrepo/junit/junit/4.12/junit-4.12.jar!/junit/framework/TestCase.class
Classpath:
target/classes:C:\Server\mavenrepo\junit\junit\4.12\junit-4.12.jar;C:\dev\EclipseWS\janino\commons-compiler\target\classes;C:\dev\EclipseWS\janino\commons-compiler-jdk\target\classes;C:\Server\mavenrepo\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;./target/classes;C:/Server/mavenrepo/junit/j
unit/4.12/junit-4.12.jar
Run trivial script:
Exception in thread "main" org.codehaus.commons.compiler.CompileException: Line 1, Column 23: package junit.framework does not exist (compiler.err.doesnt.exist)
        at org.codehaus.commons.compiler.jdk.SimpleCompiler$3.report(SimpleCompiler.java:213)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:593)
        at com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:616)
        at com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:600)
        at com.sun.tools.javac.util.Log.report(Log.java:562)
        at com.sun.tools.javac.comp.Resolve.logResolveError(Resolve.java:3473)
        at com.sun.tools.javac.comp.Resolve.accessInternal(Resolve.java:2180)
        at com.sun.tools.javac.comp.Resolve.accessBase(Resolve.java:2223)
        at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3357)
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3257)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1891)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:596)
        at com.sun.tools.javac.comp.Attr.attribType(Attr.java:658)
        at com.sun.tools.javac.comp.Attr.attribType(Attr.java:651)
        at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:836)
        at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:556)
        at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:435)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:447)
        at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:526)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:435)
        at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1024)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:497)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:475)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:985)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.codehaus.commons.compiler.jdk.SimpleCompiler.cook(SimpleCompiler.java:381)
        at org.codehaus.commons.compiler.jdk.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:198)
        at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:430)
        at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:323)
        at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:273)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:50)
        at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:570)
        at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:528)
        at datomic.JaninoRepro3.main(JaninoRepro3.java:17)

unkrig.arno@255V-N6H9 /cygdrive/c/dev/EclipseWS/janino/janino-repro-3
$
```

**Comment by stuarthalloway** [comment]
Wow, thanks for the incredibly fast response. I have tested against both the repro and against a larger project and can confirm the fix. I did have to move forward from Java 8 to Java 11 to avoid this:

```
Run trivial script:
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.CharBuffer.rewind()Ljava/nio/CharBuffer;
	at org.codehaus.commons.compiler.jdk.ClassBodyEvaluator.parseImportDeclarations(ClassBodyEvaluator.java:248)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:317)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.cook(ScriptEvaluator.java:273)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:50)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:570)
	at org.codehaus.commons.compiler.jdk.ScriptEvaluator.createFastEvaluator(ScriptEvaluator.java:528)
	at datomic.JaninoRepro3.main(JaninoRepro3.java:17)
```

Not sure if that represents a separate issue or just something odd about my local Java/maven configuration.

Thanks for all your hard work on Janino!!

**Comment by aunkrig** [comment]
```
$ for i in jdk1.6.0_43 jdk1.7.0_17 jdk1.8.0_05 jdk1.8.0_192 jdk-9.0.4 jdk-10.0.2 jdk-11.0.1; do \
> echo ================= $i; \
> jh="c:/Program Files/Java/$i"; \
> rm -f Foo.class; \
> "$jh/bin/javac" Foo.java; \
> jdisasm Foo.class|fgrep rewind; \
> done
================= jdk1.6.0_43
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.Buffer
================= jdk1.7.0_17
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.Buffer
================= jdk1.8.0_05
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.Buffer
================= jdk1.8.0_192
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.Buffer
================= jdk-9.0.4
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.CharBuffer
================= jdk-10.0.2
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.CharBuffer
================= jdk-11.0.1
        invokevirtual   java.nio.CharBuffer.rewind() => java.nio.CharBuffer
$ cat Foo.java

import java.nio.CharBuffer;

public class Foo {
        public static void main(CharBuffer cb) {
                cb.rewind();
        }
}
$
```

=> The JRE bug (?) appeared between 1.8.0_192 and 9.0.4.
