### ISSUE TITLE
IncompatibleClassChangeError when evaluating against jdk11

### ISSUE THREAD

**Issue by krizzdewizz** [janino-compiler/janino#69]
Evaluating this code against jdk11 causes an IncompatibleClassChangeError

```
ExpressionEvaluator ee = new ExpressionEvaluator();
ee.cook("java.util.stream.Stream.of(1, 2, 3)");
ee.evaluate(new Object[0]);
```
Exception:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:798)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:790)
	at ngoy.internal.parser.StreamTest.main(StreamTest.java:26)
Caused by: java.lang.IncompatibleClassChangeError: Method java.util.stream.Stream.of([Ljava/lang/Object;)Ljava/util/stream/Stream; must be InterfaceMethodref constant
	at SC.eval0(Unknown Source)
	... 7 more
```

java -version:
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by aunkrig** [comment]
Reproducable with these JREs:

* jdk-9-157
* openjdk-10.0.2
* openjdk-ea+26
* openjdk-12-ea+6

**Comment by aunkrig** [comment]
JDK 11 produces:

    //   #4: InterfaceMethodref: java.util.stream.Stream::java.util.stream.Stream.of(Object[]) => java.util.stream.Stream
    java.util.stream.Stream.of(Object[]) => java.util.stream.Stream (4)

JANINO generates:

    //   #18: Methodref: java.util.stream.Stream::java.util.stream.Stream.of(Object[]) => java.util.stream.Stream
    java.util.stream.Stream.of(Object[]) => java.util.stream.Stream (18)

That leads to the `IncompatibleClassChangeError`.

**Comment by aunkrig** [comment]
When I change the `Methodref` to `InterfaceMethodref`, I get THIS result:

```
java.lang.VerifyError: Illegal type at constant pool entry 18 in class SC
Exception Details:
  Location:
    SC.eval0()Ljava/lang/Object; @25: invokestatic
  Reason:
    Constant pool index 18 is invalid
  Bytecode:
    0000000: 06bd 0004 5903 04b8 000c 5359 0405 b800
    0000010: 0c53 5905 06b8 000c 53b8 0012 b0       

	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
	at org.codehaus.janino.ScriptEvaluator.cook2(ScriptEvaluator.java:748)
        ...
```

WTF?!

**Comment by aunkrig** [comment]
Uh-oh... When I set `ClassFile.majorVersion` to `MAJOR_VERSION_JDK_1_8` or later, then it works like a breeze... unfortunately `ClassFile.majorVersion` must remain fixed to 1.6 as long as we don't generate a `StackMapTable` attribute.

The summary is: You cannot invoke static interface methods from JANINO-generated code. Dammit.

I have to think about this one. Stay tuned.

**Comment by aunkrig** [comment]
Janino now generates Java 8 .class files and can thus invoke static interface methods. See ```org.codehaus.commons.compiler.tests.ReportedBugsTest.testIssue69_IncompatibleClassChangeError_when_evaluating_against_janino9plus()```.

Please test!

**Comment by vlsi** [comment]
I tried upgrading Janino in mat-calcite-plugin -> Apache Calcite -> Janino setup, however, the error I get is as follows.

I assume target bytecode should be configured in Calcite (https://issues.apache.org/jira/browse/CALCITE-4328)

```
Caused by: org.codehaus.commons.compiler.CompileException: Line 26, Column 71: Invocation of static interface methods only available for target version 8+
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12631)
	at org.codehaus.janino.UnitCompiler.invoke(UnitCompiler.java:12754)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5213)
	at org.codehaus.janino.UnitCompiler.access$9000(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitMethodInvocation(UnitCompiler.java:4599)
	at org.codehaus.janino.UnitCompiler$15.visitMethodInvocation(UnitCompiler.java:4572)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5443)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4572)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5696)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5655)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5624)
	at org.codehaus.janino.UnitCompiler.access$9600(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitNewInitializedArray(UnitCompiler.java:4610)
	at org.codehaus.janino.UnitCompiler$15.visitNewInitializedArray(UnitCompiler.java:4572)
	at org.codehaus.janino.Java$NewInitializedArray.accept(Java.java:5743)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4572)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5696)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2709)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1540)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3886)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3497)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3201)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:977)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:947)
	at org.codehaus.janino.UnitCompiler.access$200(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:389)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$AnonymousClassDeclaration.accept(Java.java:1375)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5539)
	at org.codehaus.janino.UnitCompiler.access$9400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4608)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4572)
	at org.codehaus.janino.Java$NewAnonymousClassInstance.accept(Java.java:5608)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4572)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5696)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2709)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1540)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3886)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3497)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3201)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:977)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:947)
	at org.codehaus.janino.UnitCompiler.access$200(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:389)
	at org.codehaus.janino.UnitCompiler$2.visitAnonymousClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$AnonymousClassDeclaration.accept(Java.java:1375)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5539)
	at org.codehaus.janino.UnitCompiler.access$9400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4608)
	at org.codehaus.janino.UnitCompiler$15.visitNewAnonymousClassInstance(UnitCompiler.java:4572)
	at org.codehaus.janino.Java$NewAnonymousClassInstance.accept(Java.java:5608)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4572)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5696)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2709)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1540)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1523)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3886)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1607)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3497)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3201)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1379)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1352)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:800)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:412)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:391)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:386)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1692)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:386)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:359)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:231)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:333)
	at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:330)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:367)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:330)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:245)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:267)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:52)
	at org.codehaus.janino.ClassBodyEvaluator.createInstance(ClassBodyEvaluator.java:428)
	at org.apache.calcite.adapter.enumerable.EnumerableInterpretable.getBindable(EnumerableInterpretable.java:162)
	at org.apache.calcite.adapter.enumerable.EnumerableInterpretable.toBindable(EnumerableInterpretable.java:125)
```

**Comment by aunkrig** [comment]
The current version of JANINO still produces Java 6 .class files -- you must re-configure it to produce Java 8 .class files:

* Either call `setTargetVersion(8)` on the `ExpressionEvaluator` (or whatever incarnation of JANINO you use), or
* You define a system property `-DUnitCompiler.defaultTargetVersion=8`

That should eliminate the exception.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Hey vlsi,
Janino should now produce V8 .class files.
