### ISSUE TITLE
ClassNotFoundException when Janino initializes

### ISSUE THREAD

**Issue by zaoqi-unsafe** [janino-compiler/janino#87]
Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: Reading resource "/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:java/lang/Byte.class"                               at org.codehaus.janino.IClassLoader.requireType(IClassLoader.java:196)
        at org.codehaus.janino.IClassLoader.postConstruct(IClassLoader.java:132)
        at org.codehaus.janino.ResourceFinderIClassLoader.<init>(ResourceFinderIClassLoader.java:50)
        at org.codehaus.janino.IClassLoader.createJavacLikePathIClassLoader(IClassLoader.java:443)
        at org.codehaus.janino.Compiler.<init>(Compiler.java:312)                                       at org.codehaus.janino.Compiler.main(Compiler.java:166)                                 Caused by: java.lang.ClassNotFoundException: Reading resource "/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:java/lang/Byte.class"
        at org.codehaus.janino.ResourceFinderIClassLoader.findIClass(ResourceFinderIClassLoader.java:74)
        at org.codehaus.janino.IClassLoader.loadIClass(IClassLoader.java:312)
        at org.codehaus.janino.IClassLoader.requireType(IClass

**Comment by aunkrig** [comment]
Hm... your environment appears to be OpenJDK 8... would you please supply a bit more context information?

**Comment by aunkrig** [comment]
Ping.
